# NumPy Tutorial

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get Shape
b.shape

(2, 3)

In [9]:
# Get Type
a.dtype

dtype('int32')

In [10]:
# Get Size
a.itemsize
b.itemsize

8

In [11]:
# Get total size
a.nbytes

12

### Accessing/Changing specific elements, rows, columns, etc

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [13]:
# specific element [r, c]
a[1, -2]

13

In [14]:
# get a specific row or col
print(a[0]) #a[0, :]
print(a[:, 2])

[1 2 3 4 5 6 7]
[ 3 10]


In [15]:
# getting fancier [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [16]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
# 3d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific element (work outside in)
# b[0,1,1]
b[:,1,1]

array([4, 8])

In [19]:
# replace - just has to be the same dimensions
b[:,1,:] = [[9,9],[8,8]] 


### Initializing Diff types of arrays

In [20]:
# Filling with same num

# All 0s matrix
print(np.zeros((2,3)))
# All 1s matrix
print(np.ones((4,2), dtype = 'int32')) # <specifies datatype
# Other #'s
print(np.full((2,2), 99))
# Any other number (full_like)
print(np.full_like(a, 4)) # np.full(a.shape, 4) < same

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[[99 99]
 [99 99]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [21]:
# Random decimal numbers
print(np.random.rand(4,2))
# print(np.random.random_sample(a.shape))
# Random int values
print(np.random.randint(7, size=(3,3)))#<if no starting param, starts at 0

[[0.53283523 0.09956272]
 [0.56577476 0.28695706]
 [0.50816715 0.54144312]
 [0.00260863 0.52581924]]
[[5 1 4]
 [5 0 4]
 [5 0 4]]


In [22]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [24]:
# test
thing = np.ones((5,5))
thing[1:4,1:4] = 0 # thing[1:-1, 1:-1]
thing[2,2] = 9
print(thing) # holy shit im cracked

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### ***Be careful when copying arrays!***

In [25]:
a = np.array([1,2,3])
# b = a by reference
b = a.copy() # value
b[0] = 100

print(a)


[1 2 3]


#### Math

In [26]:
a = np.array([1,2,3,4])

# basic math
print(a)
print(a+2) # you could do a += 2, will do the same
print(a-2)
print(a*2)
print(a/2)
print(a ** 2)

# adding arrays
b = np.array([1,0,1,0])
print(a + b)

# sin
print(np.sin(a))
print(np.cos(a))

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[2 2 4 4]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


#### Linear Algebra

In [27]:
a = np.ones((2,3))
b = np.full((3,2), 2)
# print(a)
# print(b)
print(np.matmul(a,b))

#determinant
c = np.identity(3)
print(np.linalg.det(c))

[[6. 6.]
 [6. 6.]]
1.0


#### Stats

In [28]:
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.max(stats))
print(np.min(stats, axis=1))
print(np.max(stats, axis=0))
print(np.sum(stats, axis=0))

1
6
[1 4]
[4 5 6]
[5 7 9]


### reorganizing arrays

In [32]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8]) # sizes have to stack

print(np.vstack([v1,v2,v1,v2]))

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack((h1,h2)))


[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


### Miscellaneous

##### Load from file

In [46]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Advanced Indexing

In [56]:
# Boolean Masking and Advanced Indexing

print(filedata[filedata > 50]) # returns the values greater than 50
# you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,8]]) # a list of indexes

print(np.any(filedata > 50, axis=0)) # which collumns have a value greater than 50

print(np.all(filedata > 50, axis = 0)) # cols where all values are greater than 50

print("\nValues greater than 50 but less than 100")
print(~((filedata > 50) & (filedata < 100))) # ~ is not

[196  75 766  75  55 999  78  76  88]
[2 3 9]
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False False  True False False False False False False False
 False False False False False False]

Values greater than 50 but less than 100
[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]


In [1]:
# vanity metric