# NumPy Tutorial

In [2]:
import numpy as np

In [16]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension
a.ndim

1

In [15]:
# Get Shape
b.shape

(2, 3)

In [17]:
# Get Type
a.dtype

dtype('int16')

In [22]:
# Get Size
a.itemsize
b.itemsize

8

In [21]:
# Get total size
a.nbytes

6

### Accessing/Changing specific elements, rows, columns, etc

In [23]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [25]:
# specific element [r, c]
a[1, -2]

13

In [29]:
# get a specific row or col
print(a[0]) #a[0, :]
print(a[:, 2])

[1 2 3 4 5 6 7]
[ 3 10]


In [31]:
# getting fancier [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [34]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [37]:
# 3d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get specific element (work outside in)
# b[0,1,1]
b[:,1,1]

array([4, 8])

In [42]:
# replace - just has to be the same dimensions
b[:,1,:] = [[9,9],[8,8]] 


### Initializing Diff types of arrays

In [60]:
# Filling with same num

# All 0s matrix
print(np.zeros((2,3)))
# All 1s matrix
print(np.ones((4,2), dtype = 'int32')) # <specifies datatype
# Other #'s
print(np.full((2,2), 99))
# Any other number (full_like)
print(np.full_like(a, 4)) # np.full(a.shape, 4) < same

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[[99 99]
 [99 99]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [83]:
# Random decimal numbers
print(np.random.rand(4,2))
# print(np.random.random_sample(a.shape))
# Random int values
print(np.random.randint(7, size=(3,3)))#<if no starting param, starts at 0

[[0.67453814 0.57886949]
 [0.11362899 0.63969325]
 [0.66022294 0.0934993 ]
 [0.8700079  0.30475673]]
[[3 1 3]
 [5 6 4]
 [4 6 1]]


In [85]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [99]:
# test
thing = np.ones((5,5))
thing[1:4,1:4] = 0 # thing[1:-1, 1:-1]
thing[2,2] = 9
print(thing) # holy shit im cracked

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### ***Be careful when copying arrays!***

In [104]:
a = np.array([1,2,3])
# b = a by reference
b = a.copy() # value
b[0] = 100

print(a)


[1 2 3]


#### Math

In [115]:
a = np.array([1,2,3,4])

# basic math
print(a)
print(a+2) # you could do a += 2, will do the same
print(a-2)
print(a*2)
print(a/2)
print(a ** 2)

# adding arrays
b = np.array([1,0,1,0])
print(a + b)

# sin
print(np.sin(a))
print(np.cos(a))

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[2 2 4 4]
3.5897930298416118e-09
-1.0


#### Linear Algebra

In [122]:
a = np.ones((2,3))
b = np.full((3,2), 2)
# print(a)
# print(b)
print(np.matmul(a,b))

#determinant
c = np.identity(3)
print(np.linalg.det(c))

[[6. 6.]
 [6. 6.]]
1.0


#### Stats

In [130]:
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.max(stats))
print(np.min(stats, axis=1))
print(np.max(stats, axis=0))
print(np.sum(stats, axis=0))

1
6
[1 4]
[4 5 6]
[5 7 9]
